Implement try and catch for retry pressed event
godilite/teaching-bloc pull request #3
Opened 2023-08-15 10:35 UTC by blessingwisdom

- Wrote unit test for Try and catch

2023-08-15 15:55 UTC, godilite approved these changes

2023-08-15 15:55 UTC, godilite requested changes

2023-08-15 15:55 UTC, godilite commented on lib/src/movies/domain/usecase/fetch_all_movies_use_case.dart
> +    movies.sort();
remove this sort function

2023-08-16 14:42 UTC, blessingwisdom commented on lib/src/movies/domain/usecase/fetch_all_movies_use_case.dart
> +    movies.sort();
Okay, I have removed it

2023-09-23 08:40 UTC, godilite approved these changes

2023-09-23 08:41 UTC, merged